# Generated by Django 5.2.5 on 2025-09-05 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_giver', '0002_task_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_giver.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Task',
                'verbose_name_plural': 'Saved Tasks',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
