# Generated by Django 5.2.5 on 2025-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(choices=[('Kampala', 'Kampala'), ('Wakiso', 'Wakiso'), ('Mukono', 'Mukono'), ('Mbarara', 'Mbarara'), ('Gulu', 'Gulu'), ('Jinja', 'Jinja'), ('Mbale', 'Mbale'), ('Arua', 'Arua'), ('Lira', 'Lira'), ('Masaka', 'Masaka'), ('Fort Portal', 'Fort Portal'), ('Hoima', 'Hoima'), ('Soroti', 'Soroti'), ('Masindi', 'Masindi'), ('Kabale', 'Kabale'), ('Bushenyi', 'Bushenyi'), ('Tororo', 'Tororo'), ('Iganga', 'Iganga'), ('Mityana', 'Mityana'), ('Kasese', 'Kasese')], default='Kampala', max_length=50),
        ),
    ]
