# Generated by Django 5.2.5 on 2025-09-17 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Ugandan phone number, e.g., 0772123456 or +256772123456', regex='^((\\+256|0)7(0|1|5|6|7|8|9)[0-9]{7})$')]),
        ),
    ]
