# Generated by Django 5.2.5 on 2025-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_giver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
