# Generated by Django 5.2.5 on 2025-09-15 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_giver', '0003_applications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applications',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='applications_must_be_unqiue'),
        ),
    ]
