# Generated by Django 5.2.5 on 2025-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_giver', '0004_applications_applications_must_be_unqiue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
